apiVersion: v1
kind: Pod
metadata:
  name: fresco-pod
spec:
  containers:
  - name: fresco-container
    image: nginx
    volumeMounts:
    - name: fresco-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: fresco-storage
    persistentVolumeClaim:
       claimName: fresco-pvc
